# export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
# export ANDROID_HOME=$HOME/Library/Android/sdk
# path+=("$ANDROID_HOME/emulator")
# path+=("$ANDROID_HOME/platform-tools")
