export ZSH="$HOME/.oh-my-zsh"
plugins=(git docker docker-compose nvm brew)

source $ZSH/oh-my-zsh.sh
source $HOME/Code/macsetup/env/zsh-theme.sh

path+=("/opt/homebrew/bin")
path+=("$HOME/Code/macsetup/bin")
path+=("/opt/homebrew/opt/node@20/bin")

export GOPATH="$HOME/Code/go"
path+=("$GOPATH/bin")

# export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
# export ANDROID_HOME=$HOME/Library/Android/sdk
# path+=("$ANDROID_HOME/emulator")
# path+=("$ANDROID_HOME/platform-tools")

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$PYENV_ROOT/shims:$PATH"
export PATH="$HOME/.local/bin:$PATH"

alias gpop="git reset HEAD^"
alias sbx="~/Code/sandbox.sh"
source $HOME/Code/macsetup/zshrc-user.sh
