export ZSH="$HOME/.oh-my-zsh"
plugins=(git docker docker-compose nvm brew)
source $ZSH/oh-my-zsh.sh
source $HOME/Code/macsetup/env/zsh-theme.sh
path+=("/opt/homebrew/bin")
path+=("$HOME/Code/macsetup/bin")
path+=("$HOME/.local/bin")
alias gpop="git reset HEAD^"
alias sbx="~/Code/sandbox.sh"
alias gtsync="git fetch --tags && git push origin --tags"
source $HOME/Code/macsetup/zshrc-user.sh

source $HOME/Code/macsetup/modules/go/zshrc
source $HOME/Code/macsetup/modules/java/zshrc
source $HOME/Code/macsetup/modules/node/zshrc
source $HOME/Code/macsetup/modules/python/zshrc
source $HOME/Code/macsetup/modules/ruby/zshrc
source $HOME/Code/macsetup/modules/pnpm/zshrc

export FOOO=1
